[workspace]
members = [
    "cli",
    "config",
    "db",
    "server"
]
[profile.release]
opt-level = 3
#incremental = false
#codegen-units = 1
[profile.production]
inherits = "release"
lto = "fat"
[profile.release.build-override]
opt-level = 3
#incremental = false
#codegen-units = 1

