[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9"
serde_json = "1"
sled = "0.34.7"
anyhow = "1"
log = "0.4"
config = {path = "../config"}
base64 = "0.13"
tokio = { version = "1", features = [ "rt-multi-thread", "macros", "full", "tracing", "parking_lot"] }
tokio-stream = { version = "0.1", features = [ "net" ] }
tonic = "0.8"
tonic-rpc = {version = "0.2", features = ["json", "cbor"]}
tonic-health = {version = "0.7.1", features = ["transport"]}
http = "0.2"
tower = "0.4"